FROM nginx
#removing default html
RUN rm -rf /usr/share/nginx/html/index.html
# file should be availble in current directory whare docker file exists
#COPY index.html /usr/share/nginx/html/index.html
COPY qi/usr/share/nginx/html/